#Settings
Settings:
  #Minimum Player count
  MinPLayerCount:
  #Max Player per Game
  MaxPlayercount: 10
  #Time in seconds
  TimetoPlay: 360
  #Max Seeker
  Seeker: 2
  #Max Hider
  Hider: 8
  #If a Hider got killed, he will become a Seeker(false = Not/ true = Yes)
  SwitchTeam: false
  #Time the Hider get to Hide before the Seeker will spawn(Time in seconds)
  SeekerTimetospawn: 30
  #If enabled, switch to Spectator mode after death ingame(false = Not/ true = Yes)
  Spectatormode: true
  #What happends when you join a Game which already started. If set to false you wont be able to join a running Game,else you would.(true)
  JoinRunningGame:
     #If you enable to join the running game, here you can choose which team you or other players will be in.(Set the one you like to true the rest to false)
    JoinTheRunningGameasSpectator: true
  #Enable Ability´s
  Abillity: false
