#Settings
Settings:
  #Minimum Player count
  MinPlayerCount: 4
  #Time in seconds
  TimeToPlay: 360
  #If a Hider got killed, he will become a Seeker(false = Not/ true = Yes)
  TimeToHide: 30
  #Max Seeker
  Seeker: 2
  #If a Hider got killed, he will become a Seeker(false = Not/ true = Yes)
  SwitchTeam: false
  #Time the Hider get to Hide before the Seeker will spawn(Time in seconds)
  HidingTime: 30
  #If enabled, switch to Spectator mode after death in-game(false = Not/ true = Yes)
  SpectatorMode: true
  #Enable Ability´s
  Ability:
    AbilitiesEnabled:
      AbilitiySeekerEnabled:
      AbilitiyHiderEnabled:
      AbilitiySeeker:
        Invincible:
        Blindness:
        Slowness:
        Glowing:
        Freeze:
      AbilitiyHider:
        Invincible:
        Blindness:
        Slowness:
        Glowing:
        Freeze:



#Massages
Messages:
  NoPermissionMessage: '&cYou do not have the right permission to use this.'
  GameFullMassage: '&cThe Game is already full.'

#Permission
Permissions:
  CreateSignToJoinPermission: hideandseek.createsign
  UseAdminCommand: hideandseek.admincommand
  StartGameItem: hideandseek.startitem

