name: HideAndSeek
version: '${project.version}'
main: de.theredend2000.hideandseek.Main
api-version: 1.19
authors:
  - TheRedEnd2000
  - Lumpi_2
commands:
  hideandseek:
    aliases:
      - has
      - hideseek
      - hideaseek
      - seekandhide
    description: main command